name: Run code

on:
  push:
    branches: ['master']
  
  workflow_dispatch:

jobs:
  run_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 23.4
      - name: Install Dependencies
        run: ./scripts/install.sh

      - name: Run
        # Add a MY_MNEMONIC github secret using environment variable
        env:
          # list of envs: API_HASH, API_ID, PHONE_NUMBER, USERNAME, FORWARD_TO_USERNAME, SESSION
          API_HASH: ${{ secrets.API_HASH }}
          API_ID: ${{ secrets.API_ID }}
          PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
          USERNAME: ${{ secrets.USERNAME }}
          FORWARD_TO_USERNAME: ${{ secrets.FORWARD_TO_USERNAME }}
          SESSION: ${{ secrets.SESSION }}

        run: ./scripts/run.sh